site_name: SpacePhyML
site_author: Jonah Ekelund
site_description: SpacePhyML Documentation
copyright: Copyright &copy; 2024 Jonah Ekelund

repo_url: https://github.com/Jonah-E/SpacePhyML

nav:
  - Home: index.md
  - Quick Start: quick_start.md
  - User Guide:
    - Overview: user_guide/overview.md
    - Datasets: user_guide/datasets.md
    - Dataset Creator : user_guide/dataset_creator.md
    - Examples : user_guide/examples.md

theme:
  name: mkdocs

markdown_extensions:
  - footnotes

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source
            show_source: false
            show_signature_annotations: true
            show_root_heading: true
            heading_level: 3
